name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    permissions:
        contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ { os: ubuntu-latest, rust_target: x86_64-unknown-linux-gnu }, { os: macos-latest, rust_target: x86_64-apple-darwin }, { os: macos-latest, rust_target: aarch64-apple-darwin }, { os: windows-latest, rust_target: x86_64-pc-windows-msvc } ]

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
          run_install: true

      - name: install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          override: true
          profile: minimal
          toolchain: stable
          target: ${{ matrix.platform.rust_target }}

      - uses: Swatinem/rust-cache@v2.7.0

      - name: install dependencies (ubuntu only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: tauri-build
        id: tauri_build
        uses: JonasKruckenberg/tauri-build@tauri-build-v1.4.0
        with:
          target: ${{ matrix.platform.rust_target }} 

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"
